version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - hoppscotch
    volumes:
      - C:\Users\FLynn\Desktop\data\hoppscotch\data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  hoppscotch:
    container_name: hoppscotch
    image: ling7334/hoppscotch:latest
    env_file: .env
    ports:
      - 3000:3000
      - 3100:3100
      - 3170:3170
    networks:
      - hoppscotch
    depends_on:
      postgres:
        condition: service_healthy
networks:
  hoppscotch:
    driver: bridge